using System.IO;
using ClipDesk.PluginSdk;

namespace ClipDesk.PluginSdk.Windows;

/// <summary>Adapts a file explicitly chosen/generated by the Windows renderer to the portable file contract.</summary>
public static class WindowsPluginFile
{
    public static IPluginReadableFile FromPath(string path, string? displayName = null, string? contentType = null) =>
        new LocalFile(Path.GetFullPath(path), displayName ?? Path.GetFileName(path), contentType);

    private sealed class LocalFile(string path, string name, string? contentType) : IPluginReadableFile
    {
        public string DisplayName => name;
        public string? ContentType => contentType;
        public ValueTask<Stream> OpenReadAsync(CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return ValueTask.FromResult<Stream>(File.OpenRead(path));
        }
        public ValueTask DisposeAsync() => ValueTask.CompletedTask;
    }
}
